######################################################################
#  APPLICATION (profil par défaut = local)
######################################################################

spring:
  application:
    name: auth-service
  profiles:
    default: local

  jackson:
    mapper:
      accept-case-insensitive-enums: true
    serialization:
      write-dates-as-timestamps: false

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=2000,expireAfterWrite=30s

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${app.jwt.secret}

# Exposition Actuator de base (ajuste selon besoin)
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: when_authorized

server:
  forward-headers-strategy: framework
  compression:
    enabled: true

logging:
  level:
    root: INFO
    com.mobility: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

######################################################################
#  PARAMÈTRES APPLICATIFS
######################################################################
app:
  jwt:
    secret: ${APP_JWT_SECRET:sCyaX+2NsXpvQUvJBA0Xzj6EObLLZEfggYg0RUe2D68=}
    issuer: mobility-auth
    clock-skew-sec: 60

  # CORS (lu par SecurityConfig côté code)
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - http://localhost:19006        # Expo Web
      - exp://127.0.0.1:19000         # Expo Go
    allowed-methods: [GET,POST,PUT,DELETE,OPTIONS]
    allowed-headers: ["*"]

  # Paiements : provider global + credentials par provider
  payments:
    provider: stub                     # override en prod: stripe
    accepted-providers: [STRIPE, APPLE_PAY, PAYPAL, CASH, AIRTEL_MONEY_GA]
    stripe:
      secret-key: ${STRIPE_SECRET_KEY:}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
    paypal:
      client-id: ${PAYPAL_CLIENT_ID:}
      client-secret: ${PAYPAL_CLIENT_SECRET:}
      webhook-id: ${PAYPAL_WEBHOOK_ID:}
    apple:
      merchant-id: ${APPLE_MERCHANT_ID:}
      merchant-cert: ${APPLE_MERCHANT_CERT:}
      merchant-key: ${APPLE_MERCHANT_KEY:}
    airtel-ga:
      api-key: ${AIRTEL_GA_API_KEY:}
      api-secret: ${AIRTEL_GA_API_SECRET:}
      base-url: https://openapi.airtel.africa
      webhook-secret: ${AIRTEL_GA_WEBHOOK_SECRET:}

  # Push
  push:
    provider: expo                     # override prod: fcm
    expo:
      api: https://exp.host/--/api/v2/push/send
      maxBatch: 90
    fcm:
      serverKey: ${FCM_SERVER_KEY:}
      endpoint: https://fcm.googleapis.com/fcm/send

  # Géocodage / géolocalisation
  geocoding:
    api-key: ${GEOCODING_API_KEY:}

# Résolution de devise par géoloc / pays (utilisé par CurrencyResolver)
currency:
  geo:
    enabled: true
    fallback: USD
    countryCurrencyMap:
      US: USD
      FR: EUR
      GA: XAF

# Taux de change
exchange:
  api:
    provider: exchangerate_host
    url: https://api.exchangerate.host/latest
    key: ${FX_API_KEY:}
  cacheTtlSeconds: 300

# Paramétrage Wallet (limits, kyc, idempotency, arrondis)
wallet:
  currency:
    default: USD
    rounding:
      USD: 2
      EUR: 2
      XAF: 0
  kyc:
    withdrawMinLevel: VERIFIED
  idempotency:
    enabled: true
    # délai indicatif si vous tenez un cache/mémoire (la DB reste source de vérité via unique key)
    ttlSeconds: 86400
  limits:
    XAF:
      topup:
        min: 500
        max_daily: 200000
      withdraw:
        min: 1000
        max_daily: 100000
    USD:
      topup:
        min: 2
        max_daily: 1000
      withdraw:
        min: 5
        max_daily: 500
    EUR:
      topup:
        min: 2
        max_daily: 1000
      withdraw:
        min: 5
        max_daily: 500
  payouts:
    routing:
      USD: ACH
      EUR: SEPA
      XAF: MOBILE_MONEY

# Tarification & devise par zone (utilisé aussi par CurrencyResolverImpl)
pricing:
  country:

    default:
      cityId: 0
      currency: USD
      ratePerKm:
        X:        2.90
        POOL:     2.03
        MOTO:     1.50
        COMFORT:  3.20
        XL:       4.00
        BLACK:    4.50
        LUX:      5.80
        DELIVERY: 2.90
      platformShare:
        default: 0.20

    france:        # cityId 1 — Paris
      cityId: 1
      currency: EUR
      ratePerKm:
        X:       1.90
        POOL:    1.33
        MOTO:    1.15
        COMFORT: 2.28
        XL:      2.66
        BLACK:   2.95
        LUX:     3.80
        DELIVERY: 1.90
      platformShare:
        default: 0.20

    usa:           # cityId 20 — New York
      cityId: 20
      currency: USD
      ratePerKm:
        X:       2.90
        POOL:    2.03
        MOTO:    1.89
        COMFORT: 3.48
        XL:      4.06
        BLACK:   4.50
        LUX:     5.80
        DELIVERY: 2.90
      platformShare:
        default: 0.20

    gabon:         # cityId 10 — Libreville
      cityId: 10
      currency: XAF
      ratePerKm:
        X:       250
        POOL:    225
        COMFORT: 250
        XL:      250
        BLACK:   400
        LUX:     500
        DELIVERY: 250
      flatFare:
        MOTO:
          intra_city:        2000
          libreville_akanda: 3000
      platformShare:
        default: 0.20
